### ISSUE TITLE
Upgrade the demo from 3.5.1 to 3.6

### ISSUE THREAD

**Issue by esotiri** [dvn/dvn-install-demo#3]

**Comment by pdurbin** [comment]
We probably shouldn't bother putting this pull request through QA since it's for 3.6 and 3.6.2 has been released: http://sourceforge.net/projects/dvn/files/dvn/3.6.2/

**Comment by pdurbin** [comment]
I merged #2 mostly to resolve the problem with the base box reported at https://help.hmdc.harvard.edu/Ticket/Display.html?id=180585

**Comment by pdurbin** [comment]
Minimally tested... I can log in anyway. :)
